### ISSUE TITLE
fix(testing): support application telemetry on in-memory share consumers

### ISSUE THREAD

**Issue by thomhurst** [thomhurst/Dekaf#3120]
`InMemoryShareConsumer` does not implement the optional `IApplicationTelemetryShareConsumer` capability introduced by #3119. Applications calling `RegisterMetricForSubscription` through `IKafkaShareConsumer` therefore throw `NotSupportedException` when using the first-party in-memory replacement.

This was identified by the blocking review at https://github.com/thomhurst/Dekaf/pull/3119#issuecomment-5570014937. PR #3119 merged at 2026-09-07T11:59:32Z while the follow-up fix was being validated under its canonical PR lock.

Implement the optional interface with the same argument/disposal validation and no-op behavior as `InMemoryConsumer` and `InMemoryProducer`. Add public API entries and interface/DI, validation, disposal, and non-observation tests. Keep polling and telemetry collection unchanged.

Refs #3097, #3033.
